services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        ports:
            - "8000:8000"
        networks:
            - laravel

    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "${DB_PUBLIC_PORT}:3306"
        volumes:
            - ./mariadb-data:/var/lib/mysql
        networks:
            - laravel

    mongo:
        image: mongo
        container_name: mongo
        ports:
            - "27017:27017"
        volumes:
            - ./mongo-data:/data/db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"

networks:
    laravel:
